### ISSUE TITLE
order = OrdenarEnum.DVA

### ISSUE THREAD

**Issue by laruzzo** [feslima/pyinterboleto#1]
Não é possível utilizar a classificação decrescente na API.

**Comment by laruzzo** [comment]
class OrdenarEnum(Enum):
    """Enum para ordenação do retorno da consulta.

    - NN: Nosso número (usado também para consulta do PDF do boleto);
    - SN: Seu número (que você usou na emissão);
    - DVA: Data de vencimento crescente;
    - DVD: Data de vencimento decrescente;
    - NS: Nome do sacado;
    - VA: Valor do título crescente;
    - VD: Valor do título decrescente;
    - SA: Status do título crescente;
    - SD: Status do título decrescente;
    """
    NN = 'NOSSONUMERO'
    SN = 'SEUNUMERO'
    DVA = 'DATAVENCIMENTO'
    #DVD = 'DATAVENCIMENTO'
    NS = 'NOMESACADO'
    VA = 'VALOR'
    #VD = 'VALOR'
    SA = 'STATUS'
    #SD = 'STATUS'

**Comment by feslima** [comment]
opa @laruzzo, sempre foi assim ou teve atualização na doc? eu não tenho conta PJ no inter aí não tenho acesso a documentação atualizada

**Comment by laruzzo** [comment]
Sim, tinha um erro na variável que sempre considerava null. Aí corrigi isso. Quando o código passou a considerar a variavel corretamente ele gera erro quando usa o DVD. Data de Vencimento Decrescente.

**Comment by laruzzo** [comment]
Por sinal, muito boa a sua biblioteca. Me ajudou muito. Obrigado por compartilhar e parabéns pelo trabalho.

**Comment by feslima** [comment]
Eu que agradeço a apreciação.

Mas voltando ao bug @laruzzo, é o DSC mesmo que tá dando erro? Olha, essa é a configuração do enum que testei agora:

![OrdenarEnum](https://user-images.githubusercontent.com/26683783/128407059-4c83b01e-7029-4db4-857c-c65d46c5740e.PNG)

O que tá dando erro aqui é o ASC (ascendente). Olha esse demo aqui, eu começo o STATUS_DSC e depois testo com STATUS_ASC:

![asc_dsc](https://user-images.githubusercontent.com/26683783/128407155-9036f516-cce4-487a-bd80-c01a3de51d75.gif)

**Comment by feslima** [comment]
No commit eb6766fba286a59690d212d933f4960b88693628 eu consertei (eu acho).

Também estou incluindo uma suíte de testes só pra seção de consulta. O problema é que não estou conseguindo automatizar a CI com o Actions. 

Por enquanto, até eu desenrolar isso, os testes só irão funcionar localmente com o interessado providenciando seus certificados.

**Comment by feslima** [comment]
Esqueci de agradecer pelo achado. Obrigado :)
