### ISSUE TITLE
Panda para organizar a tabela Json

### ISSUE THREAD

**Issue by laruzzo** [feslima/pyinterboleto#4]
Sugiro adicionar o panda ao código para organizar o reponse Json e apresentar os dados em tabela diretamente no terminal.

resumo = pandas.DataFrame(lista['summary'])
print(resumo)
boletos = pandas.DataFrame(lista['content'],columns={'nossoNumero', 'seuNumero', 'nomeSacado','situacao','dataVencimento','dataEmissao','valorNominal'})
print(boletos)

**Comment by feslima** [comment]
Eu optei por não usar o pandas por ser muito pesado pra uma tarefa relativamente simples. Decidi usar a lib [tabulate](https://github.com/astanin/python-tabulate) e coloquei essa representação tabulada no método \_\_str__ da classe [ResponseList](https://github.com/feslima/pyinterboleto/commit/eb6766fba286a59690d212d933f4960b88693628#diff-e7f779e9a85a7ed99859b6b56eb38b9263986de1bb74f6648c314bcd3ee722bbR116).
