### ISSUE TITLE
Variável ordernar e ordenar

### ISSUE THREAD

**Issue by laruzzo** [feslima/pyinterboleto#5]
Tem um r a mais na variável ordernar ao invés de ordenar. Então ela sempre traz valor null

        lista = get_lista_boletos(data_inicial, data_final, self.configs,
                                  filtrar=filtrar, ordernar=ordernar,
                                  page=page, size=size)

**Comment by laruzzo** [comment]
if ordernar is not None:
        params.update({'ordenarPor': ordernar.value})

**Comment by feslima** [comment]
Eu referenciei a issue errada no commit que consertei esse bug. O commit é [esse](b01d83f6cb6bccd58a4824c180e39bb38e601a56).

**Comment by feslima** [comment]
Vou fechar até mais problemas aparecerem.
